apiVersion : apps/v1
kind: Deployment
metadata:
  name: himuazuredevopsproject 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: himuazuredevopsproject
  template:
    metadata:
      labels:
        app: himuazuredevopsproject 
    spec:
      containers:
        - name: himuazuredevopsproject 
          image: himuacr.azurecr.io/himuazuredevopsproject
          ports:
          - containerPort: 80
